#!/bin/sh
version=`./getversion`
date=`date -R`
echo "version = $version"
sed -i "/^AC_INIT(findent/s/^.*/AC_INIT(findent, $version, wvermin@gmail.com)/" configure.ac    || exit 1
for d in debian debian.wheezy debian.disco debian.stretch debian.sid ; do
   if [ -e $d/changelog ] ; then
      sed -i "1s/(.*)/($version-1)/" $d/changelog       || exit 1
      sed -i "0,/^ --.*>/{/^ --.*>/s/>  .*/>  $date/}" $d/changelog || exit 1
   fi
done
autoreconf -fvi                                     || exit 1
./configure                                         || exit 1
cp test/*.f test/*.ref test/*.sh \
   test/doit debian/tests                           || exit 1
echo "Tests:" > debian/tests/control                || exit 1
for f in debian/tests/test?.sh debian/tests/test??.sh ; do
   echo "     `basename $f`" >> debian/tests/control       || exit 1
done
make builtparser builtlexer                         || exit 1
make -C src includes                                || exit 1
make distclean                                      || exit 1
echo "bootstrap done"
