#!/bin/bash
curdir=`pwd`                                       || exit 1
version=`./getversion`                             || exit 1
echo "version = $version"
./bootstrap                                        || exit 1
./configure                                        || exit 1
make -j4 distcheck                                 || exit 1
mkdir -p ../versions                               || exit 1
mv findent*.tar.gz ../versions                     || exit 1
unix2dos -n README.1st ../versions/README          || exit 1
make distclean
echo "$0 done"
