#!/bin/bash
wineserver -p
dir=`pwd`
./bootstrap                                                       || exit 1
unset CXXFLAGS
./configure --with-windows                                        || exit 1 
make clean                                                        || exit 1
rm -rf bin
make                                                              || exit 1
make check                                                        || exit 1
strip src/findent.exe                                             || exit 1
version=`./getversion`                                            || exit 1
echo "version = $version"
cd ..                                                             || exit 1
mkdir -p versions                                                 || exit 1
cp $dir/README.windows versions/README.txt                        || exit 1
cp $dir/src/findent.exe versions                                  || exit 1
cp $dir/scripts/wfindent.bat versions                             || exit 1
cp $dir/COPYING versions/COPYING.txt
cd versions                                                       || exit 1
unix2dos README.txt COPYING.txt                                   || exit 1
rm -f "findent-$version.zip"
zip   "findent-$version.zip" findent.exe README.txt \
                             COPYING.txt wfindent.bat             || exit 1
rm -f findent.exe README.txt wfindent.bat COPYING.txt
cd "$dir"                                                         || exit 1
make distclean
wineserver -k
echo "$0 done"
