#!/bin/bash
# $Id: makedeb 152 2016-12-01 15:11:07Z willem_vermin $
dir=`pwd`                                     || exit 1
version=$(./getversion)                       || exit 1
arch=`dpkg --print-architecture`              || exit 1
tar=findent-$version.tar.gz                   || exit 1
export DEB_BUILD_MAINT_OPTIONS=hardening=+all
sed -i "1s/(.*)/($version)/" debian/changelog || exit 1
#echo 'running svn commit ...'
#svn commit -m 'adapted debian/changelog' \
#              debian/changelog
#dpkg-buildpackage -us -uc                     || exit 1
#debuild -b || exit 1
debuild  || exit 1
#debsign                                       || exit 1
cd ..                                         || exit 1
gpg --verify findent_${version}_$arch.changes || exit 1
gpg --verify findent_$version.dsc             || exit 1
#echo "running lintian ..."
#lintian -i -I findent_$version*.changes       || exit 1
echo "running debc ..."
debc findent_${version}_$arch.changes         || exit 1
echo "running debi ..."                       || exit 1
sudo debi findent_${version}_$arch.changes    || exit 1
mkdir -p debian                               || exit 1
mv findent_$version* debian                   || exit 1
cd $dir                                       || exit 1
make maintainer-clean                         || exit 1
echo "running svn status ..."                 || exit 1
svn status
echo "files are in ../debian/findent_$version*" || exit 1

echo $0 done
