#!/bin/bash
curdir=$PWD
version=`./getversion`
tar=$PWD/../versions/findent-$version.tar.gz
dir=findent-$version
dsc=findent_$version-1.dsc
debdir=$PWD/../debian/findent-$version-deb
echo "version = $version"
if [ -e debian/changelog ] ; then
   sed -i "1s/(.*)/($version-1)/" debian/changelog   || exit 1
fi
rm -rf $debdir
mkdir -p $debdir || exit
cd $debdir || exit
cp $tar . || exit
tar xf $tar || exit
cd $dir || exit
cp -r $curdir/debian . || exit
dh_make --yes --s -f $tar
debuild -us -uc --lintian-opts --profile debian || exit
# dpkg-buildpackage -us -uc
cd ..
for dist in wheezy sid ; do
   echo building for $dist ...
   sudo bash `which pbuilder` --build --configfile $HOME/pbuilderrc.$dist $dsc || exit
done
echo '*************************************************'
echo '** wheezy in /var/cache/pbuilder/result-wheezy **'
echo '** sid in /var/cache/pbuilder/result-sid       **'
echo '** do not forget to debsign .changes           **'
echo '*************************************************'
echo $0 done
